FROM nvcr.io/nvidia/pytorch:24.03-py3

# Save all existing packages and versions to a text file
RUN pip list | awk '{print$1"=="$2}' | tail +3 > /root/base_constraints.txt

# Install any new packages without upgrading existing packages
RUN pip install -c /root/base_constraints.txt lightning
